ADCM-1785 Set ADCM version for used /component endpoint
arenadata/adcm_client pull request #72
Opened 2021-06-10 08:23 UTC by a-alferov

2021-06-10 11:09 UTC, vgorkavenko approved these changes

2021-06-10 11:18 UTC, dgusakov submitted a review, later dismissed

2021-06-10 11:21 UTC, vgorkavenko commented
https://allure-ee.adsw.io/launch/8445/tree/3320840?treeId=7&search=W3siaWQiOiJzdGF0dXMiLCJ0eXBlIjoidGVzdFN0YXR1c0FycmF5IiwidmFsdWUiOlsiZmFpbGVkIiwiYnJva2VuIl19XQ%3D%3D

Multijob error

2021-06-11 05:43 UTC, vgorkavenko requested changes
https://allure-ee.adsw.io/launch/8445/tree/3320840?treeId=7&search=W3siaWQiOiJzdGF0dXMiLCJ0eXBlIjoidGVzdFN0YXR1c0FycmF5IiwidmFsdWUiOlsiZmFpbGVkIiwiYnJva2VuIl19XQ%3D%3D

https://allure-ee.adsw.io/launch/8445/tree/3320513?treeId=7&search=W3siaWQiOiJzdGF0dXMiLCJ0eXBlIjoidGVzdFN0YXR1c0FycmF5IiwidmFsdWUiOlsiZmFpbGVkIiwiYnJva2VuIiwicGFzc2VkIl19XQ%3D%3D

2021-06-11 09:56 UTC, vgorkavenko approved these changes

2021-06-11 10:01 UTC, dgusakov approved these changes

2021-06-11 11:08 UTC, acmnu approved these changes

2021-06-11 11:08 UTC, merged